// <auto-generated />
using System;
using Fuelled.ClientTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fuelled.ClientTracker.Api_New.Migrations
{
    [DbContext(typeof(ClientTrackerDbContext))]
    partial class ClientTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fuelled.ClientTracker.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OnboardingStage")
                        .HasColumnType("int");

                    b.Property<string>("PolicyTypesCsv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            Name = "Hack The Box",
                            OnboardingStage = 0,
                            PolicyTypesCsv = "",
                            RenewalDate = new DateTime(2026, 6, 27, 16, 20, 48, 315, DateTimeKind.Local).AddTicks(6621),
                            StartDate = new DateTime(2025, 6, 27, 16, 20, 48, 313, DateTimeKind.Local).AddTicks(6757)
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            Name = "Forward Pursuit",
                            OnboardingStage = 0,
                            PolicyTypesCsv = "",
                            RenewalDate = new DateTime(2026, 6, 27, 16, 20, 48, 315, DateTimeKind.Local).AddTicks(6879),
                            StartDate = new DateTime(2025, 6, 27, 16, 20, 48, 315, DateTimeKind.Local).AddTicks(6873)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
